config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users
  resources :sectors
  resources :institutions do
    scope module: :institutions do
      resources :pending_documents, only: [:index]
    end
  end
  resources :document_types
  resources :state_transition_documents
  resources :document_records
  resource :deliver_document, only: [:create]
  resources :institution_searchs, only: :index

  resources :export_data, only: [:index]
  root to: 'institutions#index'
end

app/models/institution.rb
class Institution < ApplicationRecord
  self.per_page = 5
  require 'csv'

  belongs_to :sector
  has_many :document_records
  has_many :required_documents_institutions

  validates :name, presence: true, uniqueness: true

  def exists_required_document_type?(document_type)
    required_documents_institutions.where(document_type: document_type).exists?
  end

  def documents_not_registered_to_month(date:)
    document_type_ids = required_documents_institutions.pluck(:document_type_id) - document_records.where(reference_date: date.beginning_of_month..date.end_of_month).pluck(:document_type_id)
    DocumentType.where(id: document_type_ids)
  end

  def documents_with_pendency_to_month(date:)
    document_records.where.not(pendency: nil).where.not(pendency: "").where(reference_date: date.beginning_of_month..date.end_of_month)
  end

  def documents_registered_to_month(date:)
    document_type_ids = document_records.where(reference_date: date.beginning_of_month..date.end_of_month).pluck(:document_type_id)
    DocumentType.where(id: document_type_ids)
  end

  def fetch_by_status_and_date(status:, date:)
    if status == DocumentRecord::PENDING
      documents_not_registered_to_month(date:)
    elsif status == DocumentRecord::DELIVERED
      documents_registered_to_month(date:)
    end
  end

  def self.to_csv
    ::CSV.generate(headers: true) do |csv|
      csv << ["Instituição", "Documento", "Mês de Referência"]

      all.includes(:document_records).each do |institution|
        institution.document_records.each do |document|
          csv << [
            institution.name,
            DocumentType.find(document.document_type_id).name,
            document.reference_date.strftime("%Y-%m")
          ]
        end
      end
    end
  end
end

app/controllers/institutions/pending_documents_controller.rb
# frozen_string_literal: true

class Institutions::PendingDocumentsController < ApplicationController
  layout 'base'

  def index
  end
end

app/controllers/institutions_controller.rb
class InstitutionsController < ApplicationController
  layout 'base'

  def index
    @institutions = Institution.where('name LIKE ?', "%#{params[:search]}%")
    @records = @institutions.paginate(page: params[:page])
    @document_records = DocumentRecord.all
  end

  def edit
    @institution = Institution.find(params[:id])
  end

  def new
  end

  def create
    result = Institutions::Create.result(attributes: institution_params.to_h)

    if result.success?
      flash[:notice] = "#{CONSTANTS::DASHBOARD::INSTITUTION_TITLE} criada com sucesso!"
      render :new, status: :ok
    else
      flash[:notice] = "#{CONSTANTS::DASHBOARD::INSTITUTION_TITLE} não pode ser criada!"
      render :new, status: :unprocessable_entity
    end
  end

  def update
    @institution = Institution.find(params[:id])
    result = Institutions::Update.result(institution: @institution, attributes: institution_params.to_h)

    if result.success?
      flash[:notice] = "#{CONSTANTS::DASHBOARD::INSTITUTION_TITLE} atualizada com sucesso!"
      render :edit, status: :ok
    else
      flash[:notice] = "#{CONSTANTS::DASHBOARD::INSTITUTION_TITLE} não pode ser atualizada!"
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @institution = Institution.find(params[:id])
    @institution.destroy

    flash[:notice] = "#{CONSTANTS::DASHBOARD::INSTITUTION_TITLE} deletada com sucesso!"
    render :destroy, status: :ok
  rescue ActiveRecord::InvalidForeignKey => e
    flash[:notice] = "Esta #{CONSTANTS::DASHBOARD::INSTITUTION_TITLE} não pode ser deletada porque está sendo referenciada por outros registros."
    render :destroy, status: :unprocessable_entity
  end

  private
  def institution_params
    params.require(:institution).permit(:name, :sector_id, document_type_ids: [])
  end
end

app/views/institutions/destroy.turbo_stream.erb
<%= turbo_stream.update :institutions_list_frame do %>
  <%= render Table::Component.new() do |c| %>
    <% c.with_header do %>
      <th scope="col" class="px-6 py-3">
        <span class="flex items-center justify-center">Nome</span>
      </th>
      <th scope="col" class="px-6 py-3"> 
        <span class="flex items-center justify-center">Editar</span>
      </th>
      <th scope="col" class="px-6 py-3">
        <span class="flex items-center justify-center">Excluir</span>
      </th>
      <th scope="col" class="px-6 py-3">
        <span class="flex items-center justify-center">Ver recebimentos</span>
      </th>
      <th scope="col" class="px-6 py-3">
        <span class="flex items-center justify-center">Cadastrar Documento</span>
      </th>
    <% end %>
    <% c.with_set_rows do %>
      <% Institution.all&.each do |institution|%>
        <tr class="odd:bg-white odd:dark:bg-gray-900 even:bg-gray-50 even:dark:bg-gray-800 border-b dark:border-gray-700">
          <th scope="row" class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white"> <%= institution.name %> </th>
          <td class="px-6 py-4">
            <div class="flex items-center justify-center">
              <form action="<%= edit_institution_path(institution.id) %>" method="post" data-turbo="true" data-turbo-frame="form_edit_institution_content_frame" data-remote="true">
                <div data-action="click->open-modal-by-click#show">
                  <input type="hidden" name="_method" value="get">
                  <button type="submit" class="text-blue-500 hover:text-blue-700">
                    <svg class="w-6 h-6 text-gray-800 dark:text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24">
                      <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m14.304 4.844 2.852 2.852M7 7H4a1 1 0 0 0-1 1v10a1 1 0 0 0 1 1h11a1 1 0 0 0 1-1v-4.5m2.409-9.91a2.017 2.017 0 0 1 0 2.853l-6.844 6.844L8 14l.713-3.565 6.844-6.844a2.015 2.015 0 0 1 2.852 0Z"/>
                    </svg>
                  </button>
                </div>
              </form>
            </div>
          </td>
          <td class="flex items-center justify-center px-6 py-4">
            <form action="<%= institution_path(institution.id) %>" method="post" data-turbo="true" data-remote="true">
              <input type="hidden" name="_method" value="delete">
              <button type="submit" class="text-blue-500 hover:text-blue-700">
                <svg class="w-6 h-6 text-gray-800 dark:text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24">
                  <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 7h14m-9 3v8m4-8v8M10 3h4a1 1 0 0 1 1 1v3H9V4a1 1 0 0 1 1-1ZM6 7h12v13a1 1 0 0 1-1 1H7a1 1 0 0 1-1-1V7Z"/>
                </svg>
              </button>
            </form>
          </td>
          <td class="px-6 py-4 ">
            <div class="flex justify-center items-center">
              <a href="<%= document_records_path(institution_id: institution.id) %>" data-turbo="false" class="inline-flex items-center justify-center px-4 py-2 text-sm font-medium text-white border border-transparent rounded-md">
                <svg class="w-6 h-6 text-gray-800 dark:text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24">
                  <path stroke="currentColor" stroke-width="2" d="M21 12c0 1.2-4.03 6-9 6s-9-4.8-9-6c0-1.2 4.03-6 9-6s9 4.8 9 6Z"/>
                  <path stroke="currentColor" stroke-width="2" d="M15 12a3 3 0 1 1-6 0 3 3 0 0 1 6 0Z"/>
                </svg>
              </a>
            </div>
          </td>          
          <td class="px-6 py-4 ">
            <div data-controller="open-modal-by-click" class="flex justify-center items-center">
              <button type="button" data-action="click->open-modal-by-click#show" class="inline-flex items-center justify-center px-4 py-2 text-sm font-medium text-white border border-transparent rounded-md">
                <svg class="w-6 h-6 text-gray-800 dark:text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24">
                  <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 7.757v8.486M7.757 12h8.486M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z"/>
                </svg>
              </button>
              <div id="create-document_record-modal-<%= institution.id %>" data-open-modal-by-click-target="modal" tabindex="-1" aria-hidden="true" class="hidden overflow-y-auto overflow-x-hidden fixed top-0 right-0 left-0 z-50 justify-center items-center w-full md:inset-0 h-[calc(100%-1rem)] max-h-full">
                <div class="relative p-4 w-full max-w-md max-h-full">
                  <div class="relative bg-white rounded-lg shadow dark:bg-gray-700">
                    <div class="flex items-center justify-between p-4 md:p-5 border-b rounded-t dark:border-gray-600">
                      <h3 class="text-lg font-semibold text-gray-900 dark:text-white"> Registrar Recebimento </h3>
                      <button type="button" data-action="click->open-modal-by-click#hide" class="text-gray-400 bg-transparent hover:bg-gray-200 hover:text-gray-900 rounded-lg text-sm w-8 h-8 ms-auto inline-flex justify-center items-center dark:hover:bg-gray-600 dark:hover:text-white">
                        <svg class="w-3 h-3" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 14">
                          <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 6 6m0 0 6 6M7 7l6-6M7 7l-6 6" />
                        </svg>
                        <span class="sr-only">Close modal</span>
                      </button>
                    </div>

                    <%= turbo_frame_tag "form_document_record_content_frame_#{institution.id}" do %>
                      <form class="p-4 md:p-5" action=<%= document_records_path %> method="post" data-turbo="true" data-turbo-frame="form_document_record_content_frame">
                        <% form_info = { institution: institution } %>
                        <%= render 'document_records/form', form_info: form_info %>
                      </form>
                    <% end %>
                  </div>
                </div>
              </div>
            </div>
          </td>
        </tr>
      <% end %>
    <% end %>
  <% end %>
<% end %>

<%= turbo_stream.update :alert_index_frame do %>
  <div data-controller="load-flowbite">
    <%= render Alert::Component.new(title: flash.now[:notice]) %> 
  </div>
<% end %>

app/views/institutions/edit.turbo_stream.erb
<%= turbo_stream.update :form_edit_institution_content_frame do %>
  <div data-controller="load-flowbite px-2">
    <%= render Alert::Component.new(title: flash.now[:notice]) if flash.now[:notice] %> 
  </div>

  <form class="p-4 md:p-5 space-y-2" action=<%= institution_path(@institution.id) %> method="put" data-turbo="true" data-turbo-frame="form_edit_institution_content_frame">
    <div class="grid gap-4 mb-4 grid-cols-2">
      <div class="col-span-2">
        <label for="name" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Nome</label>
        <input type="text" name="institution[name]" id="name" value="<%= @institution.name %>" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500" placeholder="Nome da <%= CONSTANTS::DASHBOARD::INSTITUTION_TITLE %>" required="">
      </div>
    </div>
    <div class="col-span-2">
      <label for="sectors" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Selecione o setor</label>
      <select id="sectors" name="institution[sector_id]"class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500">
        <% Sector.all.each do |sector| %>
          <option <%= "selected" if sector.id == @institution.sector.id %> value="<%= sector.id %>"><%= sector.name %></option>
        <% end %>
      </select>
    </div>
    <div class="mb-2">
      <label for="document_types" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Selecione os tipos de documentos</label>
      <div class="grid grid-cols-2 gap-4">
        <% DocumentType.all.each do |document_type| %>
          <div class="flex items-center">
            <input type="checkbox"
                    name="institution[document_type_ids][]" 
                    id="document_type_<%= document_type.id %>" 
                    <% if @institution.exists_required_document_type?(document_type) %> checked <% end %>
                    value="<%= document_type.id %>" 
                    class="text-blue-500 focus:ring-blue-500 focus:border-blue-500 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500">
            <label for="document_type_<%= document_type.id %>" class="ms-2 text-sm text-gray-900 dark:text-white"><%= document_type.name %></label>
          </div>
        <% end %>
      </div>
    </div>
    <button type="submit" class="text-white inline-flex items-center bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">
      Salvar
    </button>
  </form>
<% end %>

<%= turbo_stream.update :institutions_list_frame do %>
  <%= render Table::Component.new() do |c| %>
    <% c.with_header do %>
      <th scope="col" class="px-6 py-3">
        <span class="flex items-center justify-center">Nome</span>
      </th>
      <th scope="col" class="px-6 py-3"> 
        <span class="flex items-center justify-center">Editar</span>
      </th>
      <th scope="col" class="px-6 py-3">
        <span class="flex items-center justify-center">Excluir</span>
      </th>
      <th scope="col" class="px-6 py-3">
        <span class="flex items-center justify-center">Ver recebimentos</span>
      </th>
      <th scope="col" class="px-6 py-3">
        <span class="flex items-center justify-center">Cadastrar Documento</span>
      </th>
    <% end %>
    <% c.with_set_rows do %>
      <% Institution.all&.each do |institution|%>
        <tr class="odd:bg-white odd:dark:bg-gray-900 even:bg-gray-50 even:dark:bg-gray-800 border-b dark:border-gray-700">
          <th scope="row" class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white"> <%= institution.name %> </th>
          <td class="px-6 py-4">
            <div class="flex items-center justify-center">
              <form action="<%= edit_institution_path(institution.id) %>" method="post" data-turbo="true" data-turbo-frame="form_edit_institution_content_frame" data-remote="true">
                <div data-action="click->open-modal-by-click#show">
                  <input type="hidden" name="_method" value="get">
                  <button type="submit" class="text-blue-500 hover:text-blue-700">
                    <svg class="w-6 h-6 text-gray-800 dark:text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24">
                      <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m14.304 4.844 2.852 2.852M7 7H4a1 1 0 0 0-1 1v10a1 1 0 0 0 1 1h11a1 1 0 0 0 1-1v-4.5m2.409-9.91a2.017 2.017 0 0 1 0 2.853l-6.844 6.844L8 14l.713-3.565 6.844-6.844a2.015 2.015 0 0 1 2.852 0Z"/>
                    </svg>
                  </button>
                </div>
              </form>
            </div>
          </td>
          <td class="flex items-center justify-center px-6 py-4">
            <form action="<%= institution_path(institution.id) %>" method="post" data-turbo="true" data-remote="true">
              <input type="hidden" name="_method" value="delete">
              <button type="submit" class="text-blue-500 hover:text-blue-700">
                <svg class="w-6 h-6 text-gray-800 dark:text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24">
                  <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 7h14m-9 3v8m4-8v8M10 3h4a1 1 0 0 1 1 1v3H9V4a1 1 0 0 1 1-1ZM6 7h12v13a1 1 0 0 1-1 1H7a1 1 0 0 1-1-1V7Z"/>
                </svg>
              </button>
            </form>
          </td>
          <td class="px-6 py-4 ">
            <div class="flex justify-center items-center">
              <a href="<%= document_records_path(institution_id: institution.id) %>" data-turbo="false" class="inline-flex items-center justify-center px-4 py-2 text-sm font-medium text-white border border-transparent rounded-md">
                <svg class="w-6 h-6 text-gray-800 dark:text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24">
                  <path stroke="currentColor" stroke-width="2" d="M21 12c0 1.2-4.03 6-9 6s-9-4.8-9-6c0-1.2 4.03-6 9-6s9 4.8 9 6Z"/>
                  <path stroke="currentColor" stroke-width="2" d="M15 12a3 3 0 1 1-6 0 3 3 0 0 1 6 0Z"/>
                </svg>
              </a>
            </div>
          </td>          
          <td class="px-6 py-4 ">
            <div data-controller="open-modal-by-click" class="flex justify-center items-center">
              <button type="button" data-action="click->open-modal-by-click#show" class="inline-flex items-center justify-center px-4 py-2 text-sm font-medium text-white border border-transparent rounded-md">
                <svg class="w-6 h-6 text-gray-800 dark:text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24">
                  <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 7.757v8.486M7.757 12h8.486M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z"/>
                </svg>
              </button>
              <div id="create-document_record-modal-<%= institution.id %>" data-open-modal-by-click-target="modal" tabindex="-1" aria-hidden="true" class="hidden overflow-y-auto overflow-x-hidden fixed top-0 right-0 left-0 z-50 justify-center items-center w-full md:inset-0 h-[calc(100%-1rem)] max-h-full">
                <div class="relative p-4 w-full max-w-md max-h-full">
                  <div class="relative bg-white rounded-lg shadow dark:bg-gray-700">
                    <div class="flex items-center justify-between p-4 md:p-5 border-b rounded-t dark:border-gray-600">
                      <h3 class="text-lg font-semibold text-gray-900 dark:text-white"> Registrar Recebimento </h3>
                      <button type="button" data-action="click->open-modal-by-click#hide" class="text-gray-400 bg-transparent hover:bg-gray-200 hover:text-gray-900 rounded-lg text-sm w-8 h-8 ms-auto inline-flex justify-center items-center dark:hover:bg-gray-600 dark:hover:text-white">
                        <svg class="w-3 h-3" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 14">
                          <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 6 6m0 0 6 6M7 7l6-6M7 7l-6 6" />
                        </svg>
                        <span class="sr-only">Close modal</span>
                      </button>
                    </div>

                    <%= turbo_frame_tag "form_document_record_content_frame_#{institution.id}" do %>
                      <form class="p-4 md:p-5" action=<%= document_records_path %> method="post" data-turbo="true" data-turbo-frame="form_document_record_content_frame">
                        <% form_info = { institution: institution } %>
                        <%= render 'document_records/form', form_info: form_info %>
                      </form>
                    <% end %>
                  </div>
                </div>
              </div>
            </div>
          </td>
        </tr>
      <% end %>
    <% end %>
  <% end %>
<% end %>