config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users
  resources :sectors
  resources :institutions do
    scope module: :institutions do
      resources :pending_documents, only: [:index]
    end
  end
  resources :document_types
  resources :state_transition_documents
  resources :document_records
  resource :deliver_document, only: [:create]
  resources :institution_searchs, only: :index

  resources :export_data, only: [:index]
  root to: 'institutions#index'
end

app/models/document_record.rb
class DocumentRecord < ActiveRecord::Base
  belongs_to :user
  belongs_to :institution
  belongs_to :document_type

  validates :reference_date, uniqueness: { scope: [:institution_id, :document_type_id] }

  PENDING = "pending"
  DELIVERED = "delivered"
end

app/controllers/document_records_controller.rb
class DocumentRecordsController < ApplicationController
  layout 'base'

  def index
    @institution = Institution.find_by(id: params[:institution_id])
    @date = Date.parse( (params[:reference_month] || Time.zone.now.prev_month.strftime("%Y-%m")) + "-01")
    @status = params[:status] || DocumentRecord::DELIVERED
    @document_types = @institution.fetch_by_status_and_date(
      status: @status,
      date: @date
    )
    @document_with_pendencies = @institution.documents_with_pendency_to_month(date: @date)
  end

  def new
    @institution_id = params[:institution_id]
    @institution = Institution.find_by(id: @institution_id)
  end

  def edit
    @document_record = DocumentRecord.find(params[:id])
  end

  def create
    @document_record = DocumentRecord.new(document_record_params.merge(user_id: current_user.id))
    @institution = @document_record.institution
    if @document_record.save
      flash[:notice] = "Registro de Documento criado com sucesso!"
    else
      flash[:notice] = "Registro de Documento não pode ser criado!"
    end
  end

  def update
    @document_record = DocumentRecord.find(params[:id])
    if @document_record.update(document_record_params)
      flash[:notice] = "Registro de Documento atualizado com sucesso!"
      render :edit, status: :ok
    else
      flash[:notice] = "Registro de Documento não pode ser atualizado!"
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @document_record = DocumentRecord.find_by(id: params[:id])
    @document_record.destroy

    redirect_to document_records_path(institution_id: @document_record.institution.id,
                                      status: DocumentRecord::DELIVERED,
                                      reference_date: @document_record.reference_date.strftime("%Y-%m"))
  end

  private

  def document_record_params
    _params = params.require(:document_record).permit(:institution_id, :state, :information, :document_type_id, :received_from, :pendency, :reference_date)
    _params[:reference_date] = (_params[:reference_date]+"-01").to_date if _params[:reference_date].present?
    _params
  end
end

app/views/document_records/_form.html.erb
<input type="hidden" id="institution_id" name="document_record[institution_id]" value="<%= form_info[:institution]&.id %>">
<input type="hidden" id="state" name="document_record[state]" value="Recebido">
<div class="grid gap-4 mb-4 grid-cols-2">
  <div class="col-span-2 mb-2">
    <label for="institutions" class="block mb-2 text-sm font-medium text-gray-900 ">Selecione o tipo de documento</label>
    <select id="institutions" name="document_record[document_type_id]"class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5      ">
      <option selected>Escolha o Tipo de Documento</option>
      <% DocumentType.all.each do |document_type| %>
        <option value="<%= document_type.id %>" <%= "selected" if document_type.id == form_info[:document_record]&.document_type&.id %> >
          <%= document_type.name %>
        </option>
      <% end %>
    </select>
  </div>
</div>
<div class="hidden grid gap-4 mb-4 grid-cols-2">
  <div class="col-span-2">
    <label for="name" class="block mb-2 text-sm font-medium text-gray-900 ">Recebido de:</label>
    <input type="text" name="document_record[received_from]" value="<%= form_info[:document_record]&.received_from %>" id="name" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5      " placeholder="Não informado">
  </div>
</div>
<div class="hidden grid gap-4 mb-4 grid-cols-2">
  <div class="col-span-2">
    <label for="name" class="block mb-2 text-sm font-medium text-gray-900 ">Informações Extras:</label>
    <input type="text" name="document_record[information]" value="<%= form_info[:document_record]&.information %>" id="name" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5      " placeholder="Sem informações extras">
  </div>
</div>
<div class="grid gap-4 mb-4 grid-cols-2">
  <div class="flex flex-col col-span-2">
    <label class="block mb-2 text-sm font-medium text-gray-900 ">Pendência:</label>
    <div class="flex flex-row space-x-2">
      <input type="text" name="document_record[pendency]" value="<%= form_info[:document_record]&.pendency %>" id="pending_information" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5      " placeholder="Sem pendência">
    </div>
  </div>
</div>
<div class="grid gap-4 mb-4 grid-cols-2">
  <div class="flex flex-col col-span-2">
    <div class="flex flex-col gap-2">
      <label class="block mb-2 text-sm font-medium text-gray-900 ">Mês de Referência:</label>
      <input type="month" 
              name="document_record[reference_date]" 
              id="reference_date" 
              <% if form_info[:document_record]&.present? %>
                value="<%= form_info[:document_record]&.reference_date&.strftime('%Y-%m') %>"
              <% else %>
                value="<%= Time.zone.now.prev_month.strftime('%Y-%m') %>"
              <% end %>
              class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5      " placeholder="">
    </div>
  </div>
</div>
<button type="submit" class="text-white inline-flex items-center bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center   ">
  <svg class="me-1 -ms-1 w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
    <path fill-rule="evenodd" d="M10 5a1 1 0 011 1v3h3a1 1 0 110 2h-3v3a1 1 0 11-2 0v-3H6a1 1 0 110-2h3V6a1 1 0 011-1z" clip-rule="evenodd"></path>
  </svg> Salvar
</button>

app/views/document_records/create.turbo_stream.erb
<%= turbo_stream.update "form_document_record_content_frame_#{@institution.id}" do %>
  <div data-controller="load-flowbite">
    <%= render Alert::Component.new(title: flash.now[:notice]) %>
  </div>
  <form class="p-4 md:p-5" action=<%= document_records_path %> method="post" data-turbo="true" data-turbo-frame="form_document_record_content_frame">
    <% form_info = { institution: @institution } %>
    <%= render 'document_records/form', form_info: form_info %>
  </form>
<% end %>

app/views/document_records/destroy.turbo_stream.erb
<%= turbo_stream.update :document_records_list_frame do %>
  <%= render Table::Component.new() do |c| %>
    <% c.with_header do %>
      <th scope="col" class="px-6 py-3"> Documento </th>
      <th scope="col" class="px-6 py-3"> Data da Entrega </th>
      <th scope="col" class="px-6 py-3"> Estado </th>
      <th scope="col" class="px-6 py-3"> <%= CONSTANTS::DASHBOARD::INSTITUTION_TITLE %> </th>
      <th scope="col" class="px-6 py-3"> Editar </th>
      <th scope="col" class="px-6 py-3"> Excluir </th>
    <% end %>
    <% c.with_set_rows do %>
      <% DocumentRecord.all&.each do |document_record|%>
        <tr class="odd:bg-white odd:dark:bg-gray-900 even:bg-gray-50 even:dark:bg-gray-800 border-b dark:border-gray-700">
          <th scope="row" class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white"> <%= document_record.document_type.name %> </th>
          <td class="px-6 py-4">
            <%= document_record.created_at.strftime("%d/%m/%Y às %H:%M") %>
          </td>
          <td class="px-6 py-4">
            <% if document_record.state %>
              <span class="bg-green-100 text-green-800 text-xs font-medium me-2 px-2.5 py-0.5 rounded dark:bg-green-900 dark:text-green-300">Entregue</span>
            <% else %>
              <span class="bg-red-100 text-red-800 text-xs font-medium me-2 px-2.5 py-0.5 rounded dark:bg-red-900 dark:text-red-300">Não Entregue</span>
            <% end %>
          </td>
          <td class="px-6 py-4">
            <%= document_record.institution.name %>
          </td>
          <td class="px-6 py-4">
            <form action="<%= edit_document_record_path(document_record.id) %>" method="post" data-turbo="true" data-turbo-frame="form_edit_document_record_content_frame" data-remote="true">
              <div data-action="click->open-modal-by-click#show">
                <input type="hidden" name="_method" value="get">
                <button type="submit" class="text-blue-500 hover:text-blue-700">Editar</button>
              </div>
            </form>
          </td>
          <td class="px-6 py-4"> <a href="#" class="text-blue-500 hover:text-blue-700"> Excluir </a> </td>
        </tr>
      <% end %>
    <% end %>
  <% end %>
<% end %>

app/views/document_records/edit.turbo_stream.erb
<%= turbo_stream.update :form_edit_document_record_content_frame do %>
  <div data-controller="load-flowbite">
    <% if flash.now[:notice].present? %>
      <%= render Alert::Component.new(title: flash.now[:notice]) %> 
    <% end %>
  </div>
  <form class="p-4 md:p-5" action=<%= document_record_path %> method="put" data-turbo="true" data-turbo-frame="form_document_record_content_frame">
    <% form_info = { institution: @document_record.institution, document_record: @document_record } %>
    <%= render 'document_records/form', form_info: form_info %>
  </form>
<% end %>

<%= turbo_stream.update :document_records_list_frame do %>
  <%= render Table::Component.new() do |c| %>
    <% c.with_header do %>
      <th scope="col" class="px-6 py-3"> Documento </th>
      <th scope="col" class="px-6 py-3"> Data da Entrega </th>
      <th scope="col" class="px-6 py-3"> Estado </th>
      <th scope="col" class="px-6 py-3"> <%= CONSTANTS::DASHBOARD::INSTITUTION_TITLE %> </th>
      <th scope="col" class="px-6 py-3"> Editar </th>
      <th scope="col" class="px-6 py-3"> Excluir </th>
    <% end %>
    <% c.with_set_rows do %>
      <% DocumentRecord.all&.each do |document_record|%>
        <tr class="odd:bg-white odd:dark:bg-gray-900 even:bg-gray-50 even:dark:bg-gray-800 border-b dark:border-gray-700">
          <th scope="row" class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white"> <%= document_record.document_type.name %> </th>
          <td class="px-6 py-4">
            <%= document_record.created_at.strftime("%d/%m/%Y às %H:%M") %>
          </td>
          <td class="px-6 py-4">
            <% if document_record.state %>
              <span class="bg-green-100 text-green-800 text-xs font-medium me-2 px-2.5 py-0.5 rounded dark:bg-green-900 dark:text-green-300">Entregue</span>
            <% else %>
              <span class="bg-red-100 text-red-800 text-xs font-medium me-2 px-2.5 py-0.5 rounded dark:bg-red-900 dark:text-red-300">Não Entregue</span>
            <% end %>
          </td>
          <td class="px-6 py-4">
            <%= document_record.institution.name %>
          </td>
          <td class="px-6 py-4">
            <form action="<%= edit_document_record_path(document_record.id) %>" method="post" data-turbo="true" data-turbo-frame="form_edit_document_record_content_frame" data-remote="true">
              <div data-action="click->open-modal-by-click#show">
                <input type="hidden" name="_method" value="get">
                <button type="submit" class="text-blue-500 hover:text-blue-700">Editar</button>
              </div>
            </form>
          </td>
          <td class="px-6 py-4"> <a href="#" class="text-blue-500 hover:text-blue-700"> Excluir </a> </td>
        </tr>
      <% end %>
    <% end %>
  <% end %>
<% end %>

app/views/document_records/index.html.erb
<section>
  <h1 class="font-bold mb-2"><%= @institution.name %></h1>
  <h1 class="font-bold">Meses com pendências do ano atual</h1>
  <div class="flex flex-col">
    <div class="flex flex-row w-1/3">
      <div class="flex flex-row">
        <% if Date.new(Date.today.year, 1, 1).past? && @institution.fetch_by_status_and_date(status: DocumentRecord::PENDING, date: Date.new(Date.today.year, 1, 1)).exists? %>
          <%= link_to "Janeiro", document_records_path(institution_id: @institution.id, status: DocumentRecord::PENDING, reference_month: Date.new(Date.today.year, 1, 1).strftime("%Y-%m")), class: "hover:underline hover:text-blue-400" %>
          <span class="flex w-3 h-3 me-3 bg-yellow-300 rounded-full"></span>
        <% end %>
      </div>
      <div class="flex flex-row">
        <% if Date.new(Date.today.year, 2, 1).past? && @institution.fetch_by_status_and_date(status: DocumentRecord::PENDING, date: Date.new(Date.today.year, 2, 1)).exists? %>
          <%= link_to "Fevereiro", document_records_path(institution_id: @institution.id, status: DocumentRecord::PENDING, reference_month: Date.new(Date.today.year, 2, 1).strftime("%Y-%m")), class: "hover:underline hover:text-blue-400" %>
          <span class="flex w-3 h-3 me-3 bg-yellow-300 rounded-full"></span>
        <% end %>
      </div>
      <div class="flex flex-row">
        <% if Date.new(Date.today.year, 3, 1).past? && @institution.fetch_by_status_and_date(status: DocumentRecord::PENDING, date: Date.new(Date.today.year, 3, 1)).exists? %>
          <%= link_to "Março", document_records_path(institution_id: @institution.id, status: DocumentRecord::PENDING, reference_month: Date.new(Date.today.year, 3, 1).strftime("%Y-%m")), class: "hover:underline hover:text-blue-400" %>
          <span class="flex w-3 h-3 me-3 bg-yellow-300 rounded-full"></span>
        <% end %>
      </div>
      <div class="flex flex-row">
        <% if Date.new(Date.today.year, 4, 1).past? && @institution.fetch_by_status_and_date(status: DocumentRecord::PENDING, date: Date.new(Date.today.year, 4, 1)).exists? %>
          <%= link_to "Abril", document_records_path(institution_id: @institution.id, status: DocumentRecord::PENDING, reference_month: Date.new(Date.today.year, 4, 1).strftime("%Y-%m")), class: "hover:underline hover:text-blue-400" %>
          <span class="flex w-3 h-3 me-3 bg-yellow-300 rounded-full"></span>
        <% end %>
      </div>
    </div>
    <div class="flex flex-row w-1/3">
      <div class="flex flex-row">
        <% if Date.new(Date.today.year, 5, 1).past? && @institution.fetch_by_status_and_date(status: DocumentRecord::PENDING, date: Date.new(Date.today.year, 5, 1)).exists? %>
          <%= link_to "Maio", document_records_path(institution_id: @institution.id, status: DocumentRecord::PENDING, reference_month: Date.new(Date.today.year, 5, 1).strftime("%Y-%m")), class: "hover:underline hover:text-blue-400" %>
          <span class="flex w-3 h-3 me-3 bg-yellow-300 rounded-full"></span>
        <% end %>
      </div>
      <div class="flex flex-row">
        <% if Date.new(Date.today.year, 6, 1).past? && @institution.fetch_by_status_and_date(status: DocumentRecord::PENDING, date: Date.new(Date.today.year, 6, 1)).exists? %>
          <%= link_to "Junho", document_records_path(institution_id: @institution.id, status: DocumentRecord::PENDING, reference_month: Date.new(Date.today.year, 6, 1).strftime("%Y-%m")), class: "hover:underline hover:text-blue-400" %>
          <span class="flex w-3 h-3 me-3 bg-yellow-300 rounded-full"></span>
        <% end %>
      </div>
      <div class="flex flex-row">
        <% if Date.new(Date.today.year, 7, 1).past? && @institution.fetch_by_status_and_date(status: DocumentRecord::PENDING, date: Date.new(Date.today.year, 7, 1)).exists? %>
          <%= link_to "Julho", document_records_path(institution_id: @institution.id, status: DocumentRecord::PENDING, reference_month: Date.new(Date.today.year, 7, 1).strftime("%Y-%m")), class: "hover:underline hover:text-blue-400" %>
          <span class="flex w-3 h-3 me-3 bg-yellow-300 rounded-full"></span>
        <% end %>
      </div>
      <div class="flex flex-row">
        <% if Date.new(Date.today.year, 8, 1).past? && @institution.fetch_by_status_and_date(status: DocumentRecord::PENDING, date: Date.new(Date.today.year, 8, 1)).exists? %>
          <%= link_to "Agosto", document_records_path(institution_id: @institution.id, status: DocumentRecord::PENDING, reference_month: Date.new(Date.today.year, 8, 1).strftime("%Y-%m")), class: "hover:underline hover:text-blue-400" %>
          <span class="flex w-3 h-3 me-3 bg-yellow-300 rounded-full"></span>
        <% end %>
      </div>
    </div>
    <div class="flex flex-row w-1/3">
      <div class="flex flex-row">
        <% if Date.new(Date.today.year, 9, 1).past? && @institution.fetch_by_status_and_date(status: DocumentRecord::PENDING, date: Date.new(Date.today.year, 9, 1)).exists? %>
          <%= link_to "Setembro", document_records_path(institution_id: @institution.id, status: DocumentRecord::PENDING, reference_month: Date.new(Date.today.year, 9, 1).strftime("%Y-%m")), class: "hover:underline hover:text-blue-400" %>
          <span class="flex w-3 h-3 me-3 bg-yellow-300 rounded-full"></span>
        <% end %>
      </div>
      <div class="flex flex-row">
        <% if Date.new(Date.today.year, 10, 1).past? && @institution.fetch_by_status_and_date(status: DocumentRecord::PENDING, date: Date.new(Date.today.year, 10, 1)).exists? %>
          <%= link_to "Outubro", document_records_path(institution_id: @institution.id, status: DocumentRecord::PENDING, reference_month: Date.new(Date.today.year, 10, 1).strftime("%Y-%m")), class: "hover:underline hover:text-blue-400" %>
          <span class="flex w-3 h-3 me-3 bg-yellow-300 rounded-full"></span>
        <% end %>
      </div>
      <div class="flex flex-row">
        <% if Date.new(Date.today.year, 11, 1).past? && @institution.fetch_by_status_and_date(status: DocumentRecord::PENDING, date: Date.new(Date.today.year, 11, 1)).exists? %>
          <%= link_to "Novembro", document_records_path(institution_id: @institution.id, status: DocumentRecord::PENDING, reference_month: Date.new(Date.today.year, 11, 1).strftime("%Y-%m")), class: "hover:underline hover:text-blue-400" %>
          <span class="flex w-3 h-3 me-3 bg-yellow-300 rounded-full"></span>
        <% end %>
      </div>
      <div class="flex flex-row">
        <% if Date.new(Date.today.year, 12, 1).past? && @institution.fetch_by_status_and_date(status: DocumentRecord::PENDING, date: Date.new(Date.today.year, 12, 1)).exists? %>
          <%= link_to "Dezembro", document_records_path(institution_id: @institution.id, status: DocumentRecord::PENDING, reference_month: Date.new(Date.today.year, 12, 1).strftime("%Y-%m")), class: "hover:underline hover:text-blue-400" %>
          <span class="flex w-3 h-3 me-3 bg-yellow-300 rounded-full"></span>
        <% end %>
      </div>
    </div>
  </div>
</section>
<section class="flex flex-col space-y-3 mt-10">
  <%= form_with url: document_records_path, method: :get, class: "flex flex-col sm:flex-row gap-2" do |form| %>
    <%= form.select :status, [["Entregues", DocumentRecord::DELIVERED], ["Pendentes", DocumentRecord::PENDING]],  :selected => @status, class: "bg-blue-200 w-full" %>
    <%= form.month_field :reference_month, value: @date, class: "w-full sm:w-content" %>
    <%= form.hidden_field :institution_id, value: @institution.id %>
    <%= form.submit "Buscar", class: "rounded-lg p-2 bg-blue-200" %>
  <% end %>
  <div class="relative overflow-x-auto shadow-md sm:rounded-lg" data-controller="open-modal-by-click">
    <% if @status == DocumentRecord::DELIVERED %>
      <p class="font-bold my-4">Documentos Recebidos</p>
    <% else %>
        <p class="font-bold my-4">Documentos obrigatórios que não foram entregues</p>
    <% end %>

    <%= turbo_frame_tag :document_records_list_frame do %>
      <%= render Table::Component.new() do |c| %>
        <% c.with_header do %>
          <th scope="col" class="px-6 py-3"> Documento </th>
          <% if @status == DocumentRecord::DELIVERED %>
            <th scope="col" class="px-6 py-3"> Excluir </th>
          <% end %>
        <% end %>
        <% c.with_set_rows do %>
          <% @document_types&.each do |document_type|%>
            <tr class="odd:bg-white odd: even:bg-gray-50 even: border-b ">
              <th scope="row" class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap "> <%= document_type.name %> </th>
              <th scope="row" class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap ">
              <% if @status == DocumentRecord::DELIVERED %>
                <%= form_with url: document_record_path(@institution.document_records.where(document_type: document_type).first), method: :delete do |form| %>
                  <%= form.hidden_field :id, value: document_type.id %>
                  <%= form.submit "Exluir", class: "rounded-lg cursor-pointer p-2 bg-red-400" %>
                <% end %>
              <% end %>
              </th>
            </tr>
          <% end %>
        <% end %>
      <% end %>
    <% end %>
    <% if @status == DocumentRecord::PENDING  && @document_with_pendencies.present? %>
      <p class="font-bold my-4">Documentos registrados com pendência</p>
      <%= render Table::Component.new() do |c| %>
        <% c.with_header do %>
          <th scope="col" class="px-6 py-3"> Documento </th>
          <th scope="col" class="px-6 py-3"> Descrição da Pendência </th>
          <th scope="col" class="px-6 py-3"> Marcar como entregue </th>
        <% end %>
        <% c.with_set_rows do %>
          <% @document_with_pendencies&.each do |document_with_pendency|%>
            <tr class="odd:bg-white odd: even:bg-gray-50 even: border-b ">
              <th scope="row" class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap "> <%= document_with_pendency.document_type.name %> </th>
              <td class="px-6 py-4 whitespace-nowrap "> <%= document_with_pendency.pendency %> </td>
              <td class="px-6 py-4 whitespace-nowrap ">
                <%= form_with url: deliver_document_path, method: :post do |form| %>
                  <%= form.hidden_field :document_record_id, value: document_with_pendency.id %>
                  <%= form.submit "Marcar como Entregue", class: "cursor-pointer rounded-lg p-2 bg-yellow-200" %>
                <% end %>
              </td>
            </tr>
          <% end %>
        <% end %>
      <% end %>
    <% end %>
  </div>
</section>

app/views/document_records/new.turbo_stream.erb
<%= turbo_stream.update "form_document_record_content_frame_#{@institution_id}" do %>
  <form class="p-4 md:p-5" action=<%= document_records_path %> method="post" data-turbo="true" data-turbo-frame="form_document_record_content_frame">
    <% form_info = { institution: @institution } %>
    <%= render 'document_records/form', form_info: form_info %>
  </form>
<% end %>