config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users
  resources :sectors
  resources :institutions do
    scope module: :institutions do
      resources :pending_documents, only: [:index]
    end
  end
  resources :document_types
  resources :state_transition_documents
  resources :document_records
  resource :deliver_document, only: [:create]
  resources :institution_searchs, only: :index

  resources :export_data, only: [:index]
  root to: 'institutions#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DocumentObtainingSystem</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/2.2.1/flowbite.turbo.min.js"></script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/base.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DocumentObtainingSystem</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <nav class="border-gray-200 bg-gray-50  ">
      <div class="max-w-screen-xl flex flex-wrap items-center justify-between mx-auto p-4">
        <a href="#" class="flex items-center space-x-3 rtl:space-x-reverse">
          <%= image_tag "logo.png", class: "h-8" %>

          <span class="self-center text-2xl font-semibold whitespace-nowrap ">RRD</span>
        </a>
        <button data-collapse-toggle="navbar-solid-bg" type="button" class="inline-flex items-center p-2 w-10 h-10 justify-center text-sm text-gray-500 rounded-lg md:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200   " aria-controls="navbar-solid-bg" aria-expanded="false">
          <span class="sr-only">Open main menu</span>
          <svg class="w-5 h-5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 17 14">
            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M1 1h15M1 7h15M1 13h15" />
          </svg>
        </button>
        <div class="hidden w-full md:block md:w-auto" id="navbar-solid-bg">
          <ul class="flex flex-col font-medium mt-4 rounded-lg bg-gray-50 md:space-x-8 rtl:space-x-reverse md:flex-row md:mt-0 md:border-0 md:bg-transparent">
            <li>
              <a href="<%= institutions_path %>" class="block py-2 px-3 md:p-0 bg-blue-700 rounded bg-transparent text-blue-700" aria-current="page"><%= CONSTANTS::DASHBOARD::INSTITUTION_TITLE %></a>
            </li>
            <li>
              <button id="dropdownNavbarLink" data-dropdown-toggle="dropdownNavbar" class="flex items-center justify-between w-full py-2 px-3 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 md:w-auto">Recursos<svg class="w-2.5 h-2.5 ms-2.5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 10 6">
                <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 4 4 4-4" />
              </svg></button>
              <div id="dropdownNavbar" class="z-10 hidden font-normal bg-white divide-y divide-gray-100 rounded-lg shadow w-44  ">
                <ul class="py-2 text-sm text-gray-700 " aria-labelledby="dropdownLargeButton">
                  <li>
                    <a href="<%= sectors_path %>" class="block px-4 py-2 hover:bg-gray-100  ">Setor</a>
                  </li>
                  <li>
                    <a href="<%= document_types_path %>" class="block px-4 py-2 hover:bg-gray-100  ">Tipos de Documentos</a>
                  </li>
                  <li>
                    <a href="<%= export_data_path(format: :csv) %>" class="block px-4 py-2 hover:bg-gray-100  ">Exportar Dados</a>
                  </li>
                </ul>
              </div>
            </li>
            <li>
              <a href="https://docs.google.com/document/d/15z5k6J9VCf7fut3dRmMoUh-v3zc1lsLHAvnsWHR41ks/edit?usp=sharing" 
                target="_blank"
                class="block py-2 px-3 md:p-0 rounded text-gray-900" aria-current="page">Como usar?</a>
            </li>
            <li>
              <%= button_to(destroy_user_session_path, data: {turbo: false}, method: :delete) do %>
                Sair
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    <div class="container block w-fit max-w-[80%] min-w-[50%] mx-auto">
      <%= yield %>
    </div>
  </body>
</html>